// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwmotlrlkjcaterjwldq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3bW90bHJsa2pjYXRlcmp3bGRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwOTA4NTIsImV4cCI6MjA3MjY2Njg1Mn0.3IBa-rfgJyqkZjNb1XiHOMzt7LQn-H301V-5KvoD4BA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});